### ISSUE TITLE
File refer to another file

### ISSUE THREAD

**Issue by BorisLeMeec** [fattynoparents/Adobe-HDS-HLS-VideoSaver#5]
Hi,

First, thank you for you extension, really helpful for me.

But for one website it finds the .m3u8 file, but says that refers to 0 file to download.
But there is a lot of file, 
![image](https://user-images.githubusercontent.com/16005667/45706120-b5301980-bb7b-11e8-8d1d-37d37403c58e.png)
![image](https://user-images.githubusercontent.com/16005667/45706159-d09b2480-bb7b-11e8-908f-b344603b17e3.png)

This screenshot shows you how this is.

How can I download the video ? 

Thank you a lot

**Comment by fattynoparents** [comment]
Hi, could you please give me a link to the video? I will check this issue. Thanks!

**Comment by BorisLeMeec** [comment]
Yeah sure, sorry for the late answer : 
https://www.tvr.bzh/programmes/tvr-politique-1515756600

**Comment by fattynoparents** [comment]
Fixed this in v2.8.5. 
Also uploaded a new version where it's possible to input m3u8 links manually.

**Comment by BorisLeMeec** [comment]
Dude, you're the best. Thank you a lot.
